export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const COMPLETE_TODO = 'COMPLETE_TODO'
export const COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const SELECT_USER = 'SELECT_USER'
export const SELECT_TASK = 'SELECT_TASK'
export const TASK_DONE = 'TASK_DONE'
export const ADD_TASK = 'ADD_TASK'


